name: NexusMap

services:
  db:
    container_name: NexusMapDb
    image: mariadb:10.5.8
    env_file:
      - ./config/mysql.env
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - "3306:3306"
    networks:
      shared_network:
        ipv4_address: 172.23.0.102
    volumes:
      - ./config:/config
      - ./var/db:/var/lib/mysql

  data_analysis:
    container_name: NexusMapDataAnalysis
    build:
      context: ./app/data_analysis
      dockerfile: ../../docker/python/Dockerfile
    networks:
      - shared_network
    volumes:
      - ./app/data_analysis:/app/data_analysis
    depends_on:
      - db

  api:
    container_name: NexusMapAPI
    build:
      context: ./app/api
      dockerfile: ../../docker/php/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      shared_network:
        ipv4_address: 172.23.0.100
    volumes:
      - ./var/projects:/userfiles
      - ./config/php:/usr/local/etc/php
      - ./app/api:/var/www
      - ./app/api/public:/var/www/html

  frontend:
    container_name: NexusMapFront
    build:
      context: ./app/frontend
      dockerfile: ../../docker/php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./config/php:/usr/local/etc/php
      - ./app/frontend:/var/www
      - ./app/frontend/public:/var/www/html
    depends_on:
      - api
    networks:
      shared_network:
        ipv4_address: 172.23.0.101
    extra_hosts:
      - "api.nexusmap.l:172.23.0.100"

networks:
  shared_network:
    driver: bridge
    name: shared_network
    ipam:
      config:
        - subnet: 172.23.0.0/16