<!DOCTYPE HTML>
<html lang="{$locale}">
<head>
	<meta charset="UTF-8">
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta name="robots" content="index, follow"/>

	<meta name="description" content="" />
	<meta name="keywords" content="" />

	<style>
        @font-face {
            font-family:'FuturaPT-Book';
            src: url('https://kotasek.photos.l/fonts/FuturaPT-Book_gdi.eot');
            src: url('https://kotasek.photos.l/fonts/FuturaPT-Book_gdi.eot?#iefix') format('embedded-opentype'),
            url('https://kotasek.photos.l/fonts/FuturaPT-Book_gdi.woff') format('woff'),
            url('https://kotasek.photos.l/fonts/FuturaPT-Book_gdi.ttf') format('truetype'),
            url('https://kotasek.photos.l/fonts/FuturaPT-Book_gdi.svg#FuturaPT-Book') format('svg');
        }

        html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, font, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td {
            border: none;
            outline: 0;
            font-weight: inherit;
            font-style: inherit;
            font-size: 100%;
            font-family: inherit;
            vertical-align: baseline;
            text-decoration: none;
            margin: 0;
            padding: 0;
        }

        body {
            margin: 0;
            padding: 0;
            font-family: 'FuturaPT-Book';
        }

		* {
            font-family: 'FuturaPT-Book';
		}

		body, html {
		   height: 100%;
		   margin: 0;
		   color: #777;
		}

        .bgimg-1 {
            position: relative;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;

        }
        .bgimg-1 {
            background-image: url("http://kotasek.photos.l/upload/pages/full/500.jpg");
            height: 100%;
        }

        .caption {
            position: absolute;
            left: 0;
            top: 50%;
			margin-top:-5em;
            width: 100%;
            text-align: center;
            color: #000;
        }

        .caption span.border {
            background-color: #111;
            color: #fff;
            padding: 18px;
            font-size: 25px;
            letter-spacing: 10px;
        }

        h3 {
            letter-spacing: 5px;
            text-transform: uppercase;
            font: 20px "Lato", sans-serif;
            color: #111;
        }

		.hp-logo {
			position: absolute;
			top: 20px;
			z-index: 100;
			left: 60px;
			padding: 5px;
			background: rgba(255, 255, 255, 0.2);
        }
		.footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 50px;
            background: #fff;
            z-index: 15;
            padding: 0 50px;
            line-height: 50px;
		}
		.policy-box {
            float: left;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 1px;
            color: #666;
		}
        .policy-box span {
            float: left;
        }

        .policy-box ul {
            position: relative;
            float: left;
            margin-left: 10px;
        }

        .policy-box ul li {
            float: left;
        }

        .footer-social {
            float: right;
        }

        .policy-box ul li a {
            padding: 0 10px;
            color: #666;
        }

        .policy-box ul:before {
            content: '';
            position: absolute;
            top: 16px;
            left: -2px;
            background: #eee;
            width: 2px;
            height: 20px;
        }

        .policy-box ul li a {
            padding: 0 10px;
            color: #666;
        }
        ol, ul { list-style: none;}
	</style>
</head>
	<body>
		<div class="bgimg-1">
			<div class="caption">
				<span class="border">FULL PAGE</span><br>
				<span class="border">BACKGROUND IMAGE</span>
			</div>
			<a href="/" title="" class="hp-logo">
				<img src="http://kotasek.photos.l/images/logo.png" alt="">
			</a>
		</div>

		<div class="footer">
			<div class="policy-box">
				<span>&#169; Kotasek.eu <?php echo date('Y', time()); ?>. ALL CONTENT CAN'T BE USED WITHOUT AUTHOR PERMISSION. </span>
				<ul>
					<li><a href="mailto:tomas@kotasek.photos">tomas@kotasek.photos</a></li>
					<li>+420 774 935 427</li>
				</ul>
			</div>
			<div class="footer-social">
				<ul>
					<li>
						<a href="https://www.instagram.com/kotasek.photos/" target="_blank" >
							<i class="fa fa-instagram"></i>
						</a>
					</li>
				</ul>
			</div>
		</div>

	</body>
</html>


