<?php

declare(strict_types = 1);

namespace Api\Presenters;
use Nette\Application\UI\Presenter;

class BasePresenter extends Presenter
{

	protected function beforeRender()
	{
		parent::beforeRender(); // TODO: Change the autogenerated stub
		$this->terminate();
	}

}